services:
  - type: web
    name: gym-frontend
    env: static
    buildCommand: npm install && npm run build -- --configuration production
    staticPublishPath: dist/gym-frontend/browser
    routes:
      - type: rewrite
        source: /**
        destination: /index.html
